name: Event-sign
data:

  train_label_path: ./label/event_csl/train.pkl
  dev_label_path: ./label/event_csl/dev.pkl
  test_label_path: ./label/event_csl/test.pkl
  img_path: /path/Event_SL_720x1280/SL_raw_image/

  max_length: 300 # frame num
training:
  wandb: disabled # online or disabled
model:
 
  tokenizer: ./pretrain_lm/hftrim_mbart
  transformer:  ./pretrain_lm/hftrim_mbart
  visual_encoder: ./pretrain_lm/mbart_event_csl

