name: Event-sign
data:

  train_label_path: /path/Event_SL_720x1280/annotations/train_label_SL.pkl
  dev_label_path: /path/Event_SL_720x1280/annotations/val_label_SL.pkl
  test_label_path: /path/Event_SL_720x1280/annotations/test_label_SL.pkl
  img_path: /path/Event_SL_720x1280/SL_raw_image/

  max_length: 300 # frame num
training:
  wandb: disabled # online or disabled
model:
 
  tokenizer: ./pretrain_lm/hftrim_mbart
  transformer:  ./pretrain_lm/hftrim_mbart
  visual_encoder: ./pretrain_lm/mbart_event_csl

