name: Event-CSL
data:
  train_label_path: ./Event_CSL/label/train.pkl
  dev_label_path: ./Event_CSL/label/val.pkl
  test_label_path: ./Event_CSL/label/test.pkl
  img_path: ./Event_CSL/SL_image
  max_length: 300 # maximum frame number
training:
  wandb: disabled # online or disabled
model:
  tokenizer: ./pretrain/mBART
  transformer: ./pretrain/mBART
  visual_encoder: ./pretrain/mytran
